export const pokemonSetNames = [
    "Base Set",
    "Jungle",
    "Wizards Black Star Promos",
    "W Promotional",
    "Fossil",
    "Jumbo cards",
    "Base Set 2",
    "Team Rocket",
    "Gym Heroes",
    "Gym Challenge",
    "Neo Genesis",
    "Neo Discovery",
    "Southern Islands",
    "Neo Revelation",
    "Neo Destiny",
    "Legendary Collection",
    "Sample",
    "Expedition Base Set",
    "Best of game",
    "Aquapolis",
    "Skyridge",
    "Ruby & Sapphire",
    "Sandstorm",
    "Nintendo Black Star Promos",
    "Dragon",
    "Team Magma vs Team Aqua",
    "Hidden Legends",
    "EX trainer Kit (Latias)",
    "EX trainer Kit (Latios)",
    "Pok\u00e9 Card Creator Pack",
    "POP Series 1",
    "FireRed & LeafGreen",
    "Team Rocket Returns",
    "Deoxys",
    "Emerald",
    "POP Series 2",
    "Unseen Forces",
    "Unseen Forces Unown Collection",
    "Delta Species",
    "Legend Maker",
    "EX trainer Kit 2 (Minun)",
    "EX trainer Kit 2 (Plusle)",
    "POP Series 3",
    "Holon Phantoms",
    "POP Series 4",
    "Crystal Guardians",
    "Dragon Frontiers",
    "Power Keepers",
    "POP Series 5",
    "Diamond & Pearl",
    "DP Black Star Promos",
    "Mysterious Treasures",
    "POP Series 6",
    "DP trainer Kit (Lucario)",
    "DP trainer Kit (Manaphy)",
    "Secret Wonders",
    "Great Encounters",
    "POP Series 7",
    "Majestic Dawn",
    "Legends Awakened",
    "POP Series 8",
    "Stormfront",
    "Platinum",
    "POP Series 9",
    "Rising Rivals",
    "Supreme Victors",
    "Arceus",
    "Pok\u00e9mon Rumble",
    "HeartGold SoulSilver",
    "HGSS Black Star Promos",
    "HS trainer Kit (Raichu)",
    "HS trainer Kit (Gyarados)",
    "Unleashed",
    "Undaunted",
    "Triumphant",
    "Call of Legends",
    "Black & White",
    "BW Black Star Promos",
    "Macdonald's Collection 2011",
    "Emerging Powers",
    "BW trainer Kit (Zoroark)",
    "BW trainer Kit (Excadrill)",
    "Noble Victories",
    "Next Destinies",
    "Dark Explorers",
    "Macdonald's Collection 2012",
    "Dragons Exalted",
    "Dragon Vault",
    "Boundaries Crossed",
    "Plasma Storm",
    "Plasma Freeze",
    "Plasma Blast",
    "XY Black Star Promos",
    "Radiant Collection",
    "Legendary Treasures",
    "Kalos Starter Set",
    "Yello A Alternate",
    "XY",
    "XY trainer Kit (Sylveon)",
    "XY trainer Kit (Noivern)",
    "Flashfire",
    "Macdonald's Collection 2014",
    "Furious Fists",
    "XY trainer Kit (Wigglytuff)",
    "XY trainer Kit (Bisharp)",
    "Phantom Forces",
    "Primal Clash",
    "Double Crisis",
    "XY trainer Kit (Latios)",
    "XY trainer Kit (Latias)",
    "Roaring Skies",
    "Ancient Origins",
    "BREAKthrough",
    "Macdonald's Collection 2015",
    "BREAKpoint",
    "Generations",
    "XY trainer Kit (Pikachu Libre)",
    "XY trainer Kit (Suicune)",
    "Fates Collide",
    "Steam Siege",
    "Macdonald's Collection 2016",
    "Evolutions",
    "SM Black Star Promos",
    "Sun & Moon",
    "SM trainer Kit (Alolan Raichu)",
    "SM trainer Kit (Lycanroc)",
    "Guardians Rising",
    "Macdonald's Collection 2017",
    "Burning Shadows",
    "Shining Legends",
    "Crimson Invasion",
    "Ultra Prism",
    "Forbidden Light",
    "Celestial Storm",
    "Dragon Majesty",
    "Macdonald's Collection 2018",
    "Lost Thunder",
    "Team Up",
    "Detective Pikachu",
    "Unbroken Bonds",
    "Unified Minds",
    "Hidden Fates",
    "Yellow A Alternate",
    "Macdonald's Collection 2019",
    "Cosmic Eclipse",
    "SWSH Black Star Promos",
    "Sword & Shield",
    "Rebel Clash",
    "Darkness Ablaze",
    "Pok\u00e9mon Futsal 2020",
    "Champion's Path",
    "Vivid Voltage",
    "Macdonald's Collection 2021",
    "Shining Fates",
    "Battle Styles",
    "Chilling Reign",
    "Evolving Skies",
    "Celebrations",
    "Fusion Strike",
    "Brilliant Stars",
    "Astral Radiance",
    "Pok\u00e9mon GO",
    "Lost Origin",
    "Silver Tempest",
    "Crown Zenith",
    "SVP Black Star Promos",
    "Scarlet & Violet",
    "Paldea Evolved",
    "Obsidian Flames",
    "151",
    "Paradox Rift",
    "Paldean Fates",
    "Temporal Forces",
    "Twilight Masquerade",
    "Shrouded Fable",
    "Stellar Crown",
    "Genetic Apex",
    "Promos-A",
    "Surging Sparks",
    "Mythical Island",
    "Prismatic Evolutions",
    "Space-Time Smackdown",
    "Triumphant Light",
    "Shining Revelry",
    "Journey Together",
    "Celestial Guardians",
    "Extradimensional Crisis",
    "Destined Rivals",
    "Eevee Grove",
    "White Flare",
    "Black Bolt",
    "Wisdom of Sea and Sky"
]