// mockCategories.ts
// A simple mock DB of categories -> subcategories for a swap marketplace.

export const CATEGORIES = {
  "Furniture": [
    "Sofas & Couches",
    "Sectionals",
    "Armchairs",
    "Coffee Tables",
    "TV Stands",
    "Dining Tables",
    "Dining Chairs",
    "Beds & Frames",
    "Mattresses",
    "Dressers",
    "Wardrobes",
    "Nightstands",
    "Bookshelves",
    "Desks",
    "Office Chairs",
    "Outdoor Furniture",
  ],

  "Electronics": [
    "Smartphones",
    "Tablets",
    "Laptops",
    "Desktops",
    "Monitors",
    "Headphones",
    "Smartwatches",
    "Cameras",
    "Drones",
    "Game Consoles",
    "VR Headsets",
    "E-Readers",
    "Power Banks",
    "Cables & Adapters",
  ],

  "Phones & Tablets": [
    "iPhone",
    "Android Phones",
    "Feature Phones",
    "iPad",
    "Android Tablets",
    "Rugged Devices",
    "Cases & Covers",
    "Chargers & Cables",
    "Screen Protectors",
    "Mounts & Holders",
    "Cellular Modems",
  ],

  "Computers & Laptops": [
    "Ultrabooks",
    "Gaming Laptops",
    "Business Laptops",
    "Chromebooks",
    "Mini PCs",
    "All-in-One PCs",
    "Mac (iMac/Mac mini/MacBook)",
    "Docking Stations",
    "Laptop Chargers",
    "Carrying Bags",
  ],

  "PC Components": [
    "CPUs",
    "GPUs",
    "Motherboards",
    "RAM",
    "SSD",
    "HDD",
    "Power Supplies",
    "Cases",
    "Cooling (Air/Water)",
    "Network Cards",
    "Capture Cards",
  ],

  "Gaming": [
    "PlayStation",
    "Xbox",
    "Nintendo Switch",
    "Retro Consoles",
    "Gaming PCs",
    "Controllers",
    "Arcade Sticks",
    "Gaming Chairs",
    "Headsets",
    "Games (Physical)",
    "Games (Digital Codes)",
  ],

  "Cameras & Photography": [
    "DSLR",
    "Mirrorless",
    "Point & Shoot",
    "Lenses",
    "Tripods",
    "Gimbals",
    "Flashes & Lighting",
    "Action Cameras",
    "360 Cameras",
    "Camera Bags",
    "Memory Cards",
    "Filters",
  ],

  "Audio & Hi-Fi": [
    "Wireless Earbuds",
    "Over-Ear Headphones",
    "DAC/Amps",
    "Portable Speakers",
    "Smart Speakers",
    "Hi-Fi Systems",
    "Turntables",
    "Soundbars",
    "Microphones",
    "Studio Monitors",
  ],

  "TV & Home Theater": [
    "LED/LCD TVs",
    "OLED TVs",
    "Projectors",
    "Projection Screens",
    "AV Receivers",
    "Media Streamers",
    "Blu-ray Players",
    "TV Mounts",
    "Universal Remotes",
  ],

  "Appliances (Home)": [
    "Refrigerators",
    "Washing Machines",
    "Dryers",
    "Dishwashers",
    "Microwaves",
    "Vacuum Cleaners",
    "Robot Vacuums",
    "Air Conditioners",
    "Heaters",
    "Air Purifiers",
    "Fans",
  ],

  "Kitchenware": [
    "Cookware Sets",
    "Pots & Pans",
    "Knives & Cutlery",
    "Bakeware",
    "Small Appliances",
    "Food Storage",
    "Water Filters",
    "Coffee & Tea",
    "Dinnerware",
    "Glassware",
    "Utensils",
  ],

  "Home Decor": [
    "Rugs",
    "Curtains",
    "Mirrors",
    "Wall Art",
    "Clocks",
    "Vases",
    "Candles",
    "Bedding",
    "Cushions & Throws",
    "Shelving",
  ],

  "Lighting": [
    "Floor Lamps",
    "Table Lamps",
    "Ceiling Lights",
    "Pendant Lights",
    "Wall Lights",
    "LED Strips",
    "Smart Bulbs",
    "Outdoor Lighting",
    "Desk Lamps",
  ],

  "Tools & Hardware": [
    "Hand Tools",
    "Power Tools",
    "Tool Storage",
    "Compressors",
    "Welding",
    "Saws & Blades",
    "Drills & Drivers",
    "Meters & Testers",
    "Ladders",
    "Fasteners",
    "Safety Gear",
  ],

  "Garden & Outdoor": [
    "Grills & BBQ",
    "Patio Sets",
    "Umbrellas",
    "Outdoor Storage",
    "Planters",
    "Lawn Mowers",
    "Trimmers",
    "Pressure Washers",
    "Hoses & Fittings",
    "Garden Tools",
  ],

  "Sports Equipment": [
    "Ball Sports",
    "Racket Sports",
    "Water Sports",
    "Winter Sports",
    "Team Sports",
    "Combat Sports",
    "Climbing",
    "Skateboarding",
    "Scooters",
    "Sports Bags",
    "Protective Gear",
  ],

  "Fitness & Gym": [
    "Dumbbells",
    "Kettlebells",
    "Barbells & Plates",
    "Benches",
    "Racks",
    "Treadmills",
    "Bikes",
    "Rowers",
    "Resistance Bands",
    "Mats",
    "Wearables",
  ],

  "Bicycles & Scooters": [
    "Road Bikes",
    "Mountain Bikes",
    "Hybrid/City",
    "Electric Bikes",
    "Kids Bikes",
    "Folding Bikes",
    "Scooters (Kick)",
    "E-Scooters",
    "Helmets",
    "Locks",
    "Lights",
  ],

  "Automotive Parts": [
    "Wheels & Tires",
    "Exterior",
    "Interior",
    "Audio & Navigation",
    "Batteries",
    "Engine Parts",
    "Suspension",
    "Brakes",
    "Fluids & Oils",
    "Tools & Diagnostics",
  ],

  "Motorcycle Gear": [
    "Helmets",
    "Jackets",
    "Gloves",
    "Boots",
    "Pants",
    "Body Armor",
    "Luggage",
    "Parts & Spares",
    "Maintenance",
    "Comms & GPS",
  ],

  "Baby & Toddler": [
    "Strollers",
    "Car Seats",
    "High Chairs",
    "Cribs",
    "Monitors",
    "Carriers",
    "Feeding",
    "Bathing",
    "Safety",
    "Toys (0-3)",
  ],

  "Kids & Toys": [
    "STEM Toys",
    "Building Sets",
    "Action Figures",
    "Dolls",
    "RC Toys",
    "Outdoor Play",
    "Educational",
    "Stuffed Animals",
    "Pretend Play",
    "Ride-Ons",
  ],

  "Board Games & Puzzles": [
    "Strategy",
    "Party",
    "Co-op",
    "Family",
    "War Games",
    "Abstract",
    "Card Games",
    "Trading Card Supplies",
    "Puzzles (Jigsaw)",
    "Puzzle Accessories",
  ],

  "Trading Cards (Non-Pokémon)": [
    "Magic: The Gathering",
    "Yu-Gi-Oh!",
    "Sports Cards (Soccer)",
    "Sports Cards (Basketball)",
    "Sports Cards (Baseball)",
    "Sports Cards (NFL)",
    "One Piece TCG",
    "Dragon Ball Super",
    "Weiss Schwarz",
    "Digimon",
    "Card Supplies",
  ],

  "Pokémon Cards": [
    "Base Set",
    "Jungle",
    "Fossil",
    "Team Rocket",
    "Gym Heroes/Challenge",
    "Neo Genesis",
    "Neo Discovery",
    "Neo Revelation",
    "Neo Destiny",
    "e-Series (Expedition/Aquapolis/Skyridge)",
    "EX Series",
    "Diamond & Pearl",
    "Platinum",
    "HeartGold & SoulSilver",
    "Black & White",
    "XY",
    "Sun & Moon",
    "Sword & Shield",
    "Scarlet & Violet",
    "Promo Cards",
    "Trainer Cards",
    "Energy Cards",
    "Booster Packs",
    "Booster Boxes",
    "Elite Trainer Boxes",
    "Graded (PSA/BGS/CGC)",
    "Japanese Sets",
    "Binders & Sleeves",
    "Accessories",
  ],

  "Fashion – Men": [
    "T-Shirts",
    "Shirts",
    "Sweatshirts & Hoodies",
    "Jackets & Coats",
    "Jeans",
    "Trousers",
    "Shorts",
    "Suits & Blazers",
    "Underwear",
    "Swimwear",
    "Activewear",
  ],

  "Fashion – Women": [
    "Dresses",
    "Tops & Blouses",
    "Sweaters & Hoodies",
    "Jackets & Coats",
    "Jeans",
    "Pants & Leggings",
    "Skirts",
    "Loungewear",
    "Swimwear",
    "Activewear",
    "Maternity",
  ],

  "Shoes": [
    "Sneakers",
    "Running Shoes",
    "Hiking Boots",
    "Dress Shoes",
    "Sandals",
    "Heels",
    "Flats",
    "Loafers",
    "Kids Shoes",
    "Shoe Care",
  ],

  "Bags & Accessories": [
    "Backpacks",
    "Handbags",
    "Crossbody",
    "Travel Bags",
    "Wallets",
    "Belts",
    "Hats & Caps",
    "Scarves",
    "Sunglasses",
    "Gloves",
  ],

  "Jewelry & Watches": [
    "Necklaces",
    "Bracelets",
    "Earrings",
    "Rings",
    "Brooches",
    "Watches",
    "Watch Straps",
    "Jewelry Boxes",
    "Smartwatches",
  ],

  "Beauty & Personal Care": [
    "Skincare",
    "Haircare",
    "Makeup",
    "Fragrance",
    "Tools & Devices",
    "Men’s Grooming",
    "Bath & Body",
    "Nail Care",
    "Sun Care",
  ],

  "Health & Wellness": [
    "Supplements",
    "Massage & Recovery",
    "Braces & Supports",
    "Monitors (BP/Glucose)",
    "Aromatherapy",
    "Sleep Aids",
    "Yoga & Meditation",
  ],

  "Pet Supplies": [
    "Dog",
    "Cat",
    "Fish & Aquarium",
    "Bird",
    "Small Pets",
    "Reptile",
    "Food & Treats",
    "Beds & Furniture",
    "Carriers",
    "Grooming & Care",
    "Toys",
  ],

  "Books & Magazines": [
    "Fiction",
    "Non-Fiction",
    "Comics & Manga",
    "Textbooks",
    "Children’s Books",
    "Cookbooks",
    "Art & Design",
    "Magazines",
    "Collectible/First Editions",
  ],

  "Music (Instruments)": [
    "Guitars",
    "Basses",
    "Keyboards",
    "Pianos",
    "Drums & Percussion",
    "Brass & Woodwind",
    "Orchestral Strings",
    "DJ Gear",
    "Pedals & Effects",
    "Cases & Stands",
  ],

  "Vinyl, CDs & Audio Media": [
    "Vinyl LPs",
    "45s & Singles",
    "CDs",
    "Cassettes",
    "Box Sets",
    "Blu-ray Audio",
    "Storage & Sleeves",
    "Turntable Cartridges",
  ],

  "Art & Collectibles": [
    "Original Art",
    "Prints",
    "Photography",
    "Posters",
    "Sculpture",
    "Designer Toys",
    "Antiques",
    "Coins & Currency",
    "Stamps",
    "Autographs",
  ],

  "Crafts & DIY": [
    "Sewing",
    "Knitting & Crochet",
    "Painting & Drawing",
    "Scrapbooking",
    "3D Printing Filament",
    "Woodworking",
    "Leathercraft",
    "Beads & Jewelry Making",
    "Craft Tools",
  ],

  "Office & School": [
    "Printers",
    "Scanners",
    "Shredders",
    "Projectors",
    "Stationery",
    "Notebooks & Planners",
    "Whiteboards",
    "Chairs & Desks",
    "Organizers",
  ],

  "Smart Home & IoT": [
    "Smart Bulbs",
    "Smart Plugs",
    "Hubs",
    "Thermostats",
    "Smart Locks",
    "Smart Shades",
    "Smart Sensors",
    "Voice Assistants",
    "Home Automation",
  ],

  "Drones & RC": [
    "Camera Drones",
    "FPV Drones",
    "RC Planes",
    "RC Cars",
    "RC Boats",
    "Transmitters",
    "Batteries & Chargers",
    "Motors & Props",
    "Goggles",
    "Frames",
  ],

  "Network & Servers": [
    "Wi-Fi Routers",
    "Mesh Systems",
    "Modems",
    "Switches",
    "Server Racks",
    "NAS",
    "SFP Modules",
    "Cables",
    "UPS",
    "Firewalls",
  ],

  "Security & Surveillance": [
    "IP Cameras",
    "NVR/DVR",
    "Doorbells",
    "Smart Locks",
    "Alarms & Sensors",
    "Safes",
    "Baby Monitors",
    "Floodlights",
    "Intercoms",
  ],

  "3D Printing": [
    "FDM Printers",
    "Resin Printers",
    "Filament (PLA/ABS/PETG)",
    "Resins",
    "Nozzles & Hotends",
    "Build Plates",
    "Enclosures",
    "Calibration Tools",
  ],

  "Camping & Hiking": [
    "Tents",
    "Sleeping Bags",
    "Sleeping Pads",
    "Backpacks",
    "Camp Furniture",
    "Cookware",
    "Stoves",
    "Water Filters",
    "Lighting",
    "Navigation",
  ],

  "Travel & Luggage": [
    "Suitcases",
    "Carry-On",
    "Duffel Bags",
    "Packing Cubes",
    "Travel Pillows",
    "Adapters",
    "Locks",
    "Toiletry Bags",
    "Travel Strollers",
  ],

  "Tickets & Experiences": [
    "Concerts",
    "Sports Events",
    "Theater",
    "Festivals",
    "Theme Parks",
    "Tours",
    "Classes & Workshops",
    "Day Passes",
    "Subscriptions",
  ],

  "Gift Cards & Store Credit": [
    "Amazon",
    "Apple",
    "Google Play",
    "Steam",
    "PlayStation",
    "Xbox",
    "Nintendo",
    "eBay",
    "Retail & Fashion",
    "Restaurants",
    "Gas & Groceries",
  ],

  "Musical Equipment (Pro Audio)": [
    "Audio Interfaces",
    "Mixers",
    "Mics",
    "Stands",
    "Cables",
    "Stage Monitors",
    "In-Ear Monitors",
    "PA Speakers",
    "Lighting & FX",
    "Recorders",
  ],

  "Industrial & Lab Equipment": [
    "Power Tools (Industrial)",
    "Generators",
    "Test & Measurement",
    "3D Scanners",
    "CNC",
    "Soldering & Rework",
    "Microscopes",
    "Safety & PPE",
    "Storage & Bins",
  ],
} as const;


export const MOCK_PRODUCT_IMAGES = [
  "https://images.pexels.com/photos/2533266/pexels-photo-2533266.jpeg",
  "https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg",
  "https://images.pexels.com/photos/1738641/pexels-photo-1738641.jpeg",
  "https://images.pexels.com/photos/279480/pexels-photo-279480.jpeg",
  "https://images.pexels.com/photos/325153/pexels-photo-325153.jpeg",
  "https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg",
  "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg",
  "https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg",
  "https://images.pexels.com/photos/298864/pexels-photo-298864.jpeg",
  "https://images.pexels.com/photos/325153/pexels-photo-325153.jpeg",
  "https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg",
  "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg",
  "https://images.pexels.com/photos/274973/pexels-photo-274973.jpeg",
  "https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg",
  "https://images.pexels.com/photos/965988/pexels-photo-965988.jpeg",
  "https://images.pexels.com/photos/965986/pexels-photo-965986.jpeg",
  "https://images.pexels.com/photos/965987/pexels-photo-965987.jpeg",
  "https://images.pexels.com/photos/965985/pexels-photo-965985.jpeg",
  "https://images.pexels.com/photos/965984/pexels-photo-965984.jpeg",
  "https://images.pexels.com/photos/965983/pexels-photo-965983.jpeg",
  "https://images.pexels.com/photos/965982/pexels-photo-965982.jpeg",
  "https://images.pexels.com/photos/965981/pexels-photo-965981.jpeg",
  "https://images.pexels.com/photos/965980/pexels-photo-965980.jpeg",
  "https://images.pexels.com/photos/965979/pexels-photo-965979.jpeg",
  "https://images.pexels.com/photos/965978/pexels-photo-965978.jpeg",

] as const;

export type CategoryName = keyof typeof CATEGORIES;
export type SubcategoryName<C extends CategoryName = CategoryName> =
  (typeof CATEGORIES)[C][number];


export type ProductImageUrl = typeof MOCK_PRODUCT_IMAGES[number];
export type ProductImageArray = typeof MOCK_PRODUCT_IMAGES;